[build-system]
requires = ["setuptools>=45", "setuptools_scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "evalplus/_version.py"
version_scheme = "release-branch-semver"
local_scheme = "no-local-version"
